version: '3'
services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5431:5432"
  
  # app:
  #   depends_on:
  #     - db
  #   build:
  #     context: .
  #     dockerfile: app.Dockerfile 
  #   container_name: muso_api
  #   stdin_open: true
  #   tty: true
  #   env_file:
  #     - .env
  #   ports:
  #     - "2828:2828"
  #   network_mode: host
